version: '3.5'

services:
  pg-microservicios-usuarios:
    container_name: pg-microservicios-usuarios
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db_microservicios_usuarios